/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sungb_000' at '15. 8. 6 오후 11:02' with Gradle 2.5
 *
 * @author sungb_000, @date 15. 8. 6 오후 11:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
