DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
 USER_ID INTEGER PRIMARY KEY,
 USER_NAME VARCHAR (75),
 PASSWORD VARCHAR (75));
DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES(
 ROLE_ID INTEGER PRIMARY KEY,
 ROLE_NAME VARCHAR (20));
DROP TABLE IF EXISTS USER_ROLES;
CREATE TABLE USER_ROLES(
 USER_ID_FK INTEGER,
 ROLE_ID_FK INTEGER);